### ISSUE TITLE
pas d'attributs pour le sensor

### ISSUE THREAD

**Issue by pdecarde** [saniho/apiMareeInfo#13]
Bonjour, je suis en train d'essayer votre sensor et je ne reçois pas d'attribut comme je le vois dans la documentation. J'ai juste l'heure de la prochaine BM ou PM état). Le development à l'air super couplé avec la carte de visualization. Merci de votre aide.
Je suis sur HA PI4.
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

**Comment by saniho** [comment]
hello, qu'as-tu mis dans la config ?

**Comment by pdecarde** [comment]
Bonjour Saniho,
Excuse-moi, j'étais en congés ces dernières semaines
ma config est la suivante pour Lacanau (33):

- platform: apiMareeInfo
  code: 134
  latitude: 45.0015181
  longitude: -1.1999562
  scan_interval: 120

merci de ton aide!

**Comment by saniho** [comment]
Désolé pour le retard j'essaie de regarder ce weekend...

**Comment by saniho** [comment]
Je viens de faire un test avec ta config et cela fonctionne bien chez moi ...
Peux-tu me donner le sensor maree, et les attributs  qu'il a ?
