### ISSUE TITLE
Attributs supplémentaires

### ISSUE THREAD

**Issue by phd59** [saniho/apiMareeInfo#14]
Bonjour, pas de souci avec cette intégration, v1.0.3, HA 2022.7.3, tout roule. Bravo !
J'aimerais beaucoup obtenir aussi la hauteur actuelle, cela permettrait de faire de belles sinusoides avec une graph-card, comme sur le site du SHOM... et de connaitre la distance à parcourir pour aller me baigner ! 
Merci d'avance

**Comment by saniho** [comment]
malheureusement cette information n'est pas mise à disposition par SHOM .... donc je ne peux la redonner.
