### ISSUE TITLE
Descriptif des attributs

### ISSUE THREAD

**Issue by PolestarWx** [saniho/apiMareeInfo#17]
Bonjour,

Je vois que cette intégration dispose de très nombreux attributs au sein de l'entité, ou puis-je trouver leur signification ?

Par exemple quelle est la différence entre Coeff 0 3 et Coeff 1 3 ?

Merci pour toute aide :)

**Comment by saniho** [comment]
la documentation a été mise à jour ... details des attributs ;)

https://github.com/saniho/apiMareeInfo/blob/dev/README.md
