### ISSUE TITLE
Probleme recuperation du port 128 - ile d'aix

### ISSUE THREAD

**Issue by docteurzoidberg** [saniho/apiMareeInfo#18]
bonjour,
tout d'abord merci pour vos intégrations!

j'ai le problème suivant lorsque je configure le capteur pour le port 128 sur maree info (port de l'ile d'aix)
(probleme de parsing ?)

voici les logs:

Logger: homeassistant.components.sensor
Source: custom_components/apiMareeInfo/apiMareeInfo.py:86
Integration: Capteur (documentation, issues)
First occurred: 12:03:44 (1 occurrences)
Last logged: 12:03:44

Error while setting up apiMareeInfo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/apiMareeInfo/sensor.py", line 89, in setup_platform
    myPort.update()
  File "/config/custom_components/apiMareeInfo/sensor.py", line 62, in update
    self._myMaree.getinformationport()
  File "/config/custom_components/apiMareeInfo/apiMareeInfo.py", line 86, in getinformationport
    self._nomDuPort = jsondata["contenu"]["marees"][0]['lieu']
IndexError: list index out of range

merci d'avance !

(si j'ai un peu de temps, j'essayerai de setup un environnement de dev et de debug pour proposer un fix, mais je sais pas si je vais pouvoir)

**Comment by saniho** [comment]
Peux tu me donner la config indiqué dans ton yaml?

**Comment by docteurzoidberg** [comment]
> Peux tu me donner la config indiqué dans ton yaml?

je suis passe sur le port de la cotiniere depuis (oleron) et n'ai plus la config utilisée.

Cependant j'ai regarde, et il semblerait que le problème venait d'une liste de port différente dans l'appel a L’API pour recuperer les port et celle qui retourne les marées, de mémoire, l'une contient le port dans son résultat et pas l'autre, (peut etre du a l'apostrophe non échappé dans le nom du port dans l'url de la requête?)

l'id du port et les coordonnées devaient être les suivantes:
code: 128
latitude: 46.01
longitude: 1.10
(source: mareeinfos)

config actuelle: (port de la cotiniere, oleron)
- platform: apiMareeInfo
  code: 153
  latitude: 45.9417
  longitude: -0.953333
  scan_interval: 60

**Comment by saniho** [comment]
pour le port de l'ile d'aix, les bonnes coordonnées sont : 
latitude : 46.00940
longitude : -1.17414

cf google maps 

![image](https://user-images.githubusercontent.com/52693545/208294563-bf379fcc-88de-4030-843d-5839be570208.png)
