### ISSUE TITLE
Sensor MareeDuJour "unavailable"

### ISSUE THREAD

**Issue by noosander** [saniho/apiMareeInfo#19]
Bonjour & merci pour ton boulot.
Dernier update de apimareeinfo date du 05/12/2022
Depuis le capteur est indisponible.
Y a t'il d'autres utilisateurs dans le même cas?

**Comment by quik85** [comment]
Bonjour,
Je rencontre le même problème.

**Comment by vibi75** [comment]
Pareil... En regardant les logs, on voit que l'API non officielle a changé... :-(

**Comment by Dede29AZ** [comment]
Bonjour, je pense avoir le meme souci.
En fait j'essai depuis  ce matin d'installer le sensor et je ne le vois pas apparaitre dans l'outil de développement.
J'ai pour l'instant installer l'intégration avec HACS et mis dans mon fichier sensor.yaml les réglages de St gilles.

- platform: apiMareeInfo
  code: 124
  latitude: 46.7711
  longitude: -2.05306
  scan_interval: 120

bonne journée.

**Comment by saniho** [comment]
La nouvelle version gere la "nouvelle" api... Si vous pouvez tester et me faire un retour.

**Comment by PolestarWx** [comment]
Je veux bien tester mais il n'y a pas de doc alors je ne sais pas comment faire, pareil pour le numéro du port on trouve ça ou ?

**Comment by Dede29AZ** [comment]
Bonjour, sur un écran pas de souci mais sur smartphone les indications en haut débordent chez moi.
![Screenshot_2022-12-17-15-54-50-61_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/102630206/208248095-2debcea9-be35-4e21-aab3-480a59efdb90.jpg)
Je n'ai pas encore essayer de voir si on pouvait changer la taille de la police avec une ligne de code

**Comment by Dede29AZ** [comment]
> 

Pour le port il faut aller sur http://maree.info/3.
3 pour cet exemple pour le port de Dunkerke. c'est dans l'URL du port que tu recherches

**Comment by vibi75** [comment]
> La nouvelle version gere la "nouvelle" api... Si vous pouvez tester et me faire un retour.

Parfait pour moi, merci beaucoup !!!

**Comment by saniho** [comment]
pour information le numéro de port ne sert "plus", seule les données lat/long sont utilies.
Le numéro de port sera juste utilisé pour le nom du sensor
