### ISSUE TITLE
Entity not created

### ISSUE THREAD

**Issue by PolestarWx** [saniho/apiMareeInfo#26]
I have this configuration :

`sensor:
  - platform: apiMareeInfo
    code: 117
    latitude: 47.19
    longitude: -1.60
    scan_interval: 120
    stormio_key: xxxxxxxxxxxxxxxxxxx`

but no entity created in home assistant

**Comment by saniho** [comment]
essaye avec ceci, tu peux enlever stormio_key

platform: apiMareeInfo
code: 117
latitude: 47.19382
longitude: -2.16449
scan_interval: 120

**Comment by PolestarWx** [comment]
ça a fonctionné merci !
