### ISSUE TITLE
Home Assistant 2023.3.0 attributes size warning

### ISSUE THREAD

**Issue by Gonioul** [saniho/apiMareeInfo#27]
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:491
Integration: Recorder (documentation, issues)
First occurred: 00:19:41 (2 occurrences)
Last logged: 00:19:42

State attributes for sensor.myport_24_mareedujour exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

**Comment by PhilDev14** [comment]
Hi, i have the same Warning... i use the last version (1.14 )  :  if we look to the attributs élements (cut and past to notepad) i get  211 lines for "reels physical attributes" and  5560 lines for "Prevision informations") . it seeem that the prevision are calculated during 15 days and every hours .. perhaps,  it will be great to get the possibility to parameters theses  2 parameters (nb of days and frequency for prévisons) regards

**Comment by saniho** [comment]
[1.1.5](https://github.com/saniho/apiMareeInfo/releases/tag/v1.1.5) solved the issue
