### ISSUE TITLE
La Rochelle-Palisse sensor not created

### ISSUE THREAD

**Issue by fcrozat** [saniho/apiMareeInfo#29]
sensor:
- platform: apiMareeInfo
  code: 127
  latitude: 46.16604
  longitude: -1.21606
  scan_interval: 120

is causing a error:

Logger: homeassistant.components.sensor
Source: custom_components/apiMareeInfo/apiMareeInfo.py:141
Integration: Capteur (documentation, issues)
First occurred: 12:08:48 (1 occurrences)
Last logged: 12:08:48

Error while setting up apiMareeInfo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiMareeInfo/sensor.py", line 94, in setup_platform
    myPort.update()
  File "/config/custom_components/apiMareeInfo/sensor.py", line 64, in update
    self._myMaree.getinformationport(origine=self._origine)
  File "/config/custom_components/apiMareeInfo/apiMareeInfo.py", line 141, in getinformationport
    self._nomDuPort = jsondata["contenu"]["marees"][0]['lieu']
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
 
despite converting its coordinate to GPS to fill yaml: https://maree.info/127

**Comment by tracid56** [comment]
Hello,
Same for me :)

**Comment by saniho** [comment]
voici les "bonnes" coordonnées des ports de la rochelle : 
155 La Rochelle - Vieux-Port 46.155 -1.1533
4301 La Rochelle - Port des Minimes 46.1467 -1.1683
5189 La Rochelle 46.1613 -1.1493

**Comment by fcrozat** [comment]
Ca fonctionne pour le Vieux-Port. Pour les deux autres, il n'y a pas de remontée d'informations (mais ce n'est pas bien grave, vu qu'il n'y a les marées sont identiques pour ces 3 portsà.
