### ISSUE TITLE
Comment obtenir le code du port ?

### ISSUE THREAD

**Issue by DarKOrange75** [saniho/apiMareeInfo#4]
Bonjour @saniho,

Merci pour ce capteur ! Comment obtenir le code du port dont on veut connaître les marées ? (je cherche pour les Sables d'Olonne)

Merci encore.

**Comment by saniho** [comment]
Bonjour, le code du port est une information libre, tu peux juste indiquer 1
sinon il te faut fournir les coordonnées gps du lieu souhaité, les sables d'Olonne, c'est : 
Latitude : 46.492958
Longitude : -1.795493

ce qui donne : 
```
- platform: apiMareeInfo
  code: 1
  latitude: 46.4967
  longitude: -1.79667
  scan_interval: 120
```

**Comment by DarKOrange75** [comment]
Génial, merci beaucoup, excellente journée.
