### ISSUE TITLE
Quelle carte pour Lovelace ?

### ISSUE THREAD

**Issue by DarKOrange75** [saniho/apiMareeInfo#5]
Bonjour,

Quel est le type de carte utilisé pour afficher les données comme sur la page de présentation de ce projet ?

Merci.

**Comment by saniho** [comment]
Hello, tu peux utiliser cette card : https://github.com/saniho/content-card-maree
et ainsi avoir ceci par exemple : 
![image](https://user-images.githubusercontent.com/52693545/110255044-281eec00-7f92-11eb-86df-d7e23ecd1b6c.png)
![image](https://user-images.githubusercontent.com/52693545/110255065-3e2cac80-7f92-11eb-9353-eadfba41b754.png)

**Comment by DarKOrange75** [comment]
Excellent ! Merci beaucoup ! (Vendéen ?)
Bonne journée.
